account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
     # Access     
     path('logout/',
          auth_views.LogoutView.as_view(), name='logout'),
     path('login/',
          auth_views.LoginView.as_view(
               redirect_authenticated_user=True), name='login'),

     # Account activation
     path('activation/sent/',
          views.account_activation_sent,
          name='account_activation_sent'),
     path('activate/<uidb64>/<token>/',
          views.activate,
          name='activate'),

     # password reset with email
     path('password_reset/',
          auth_views.PasswordResetView.as_view(
               success_url=reverse_lazy('account:password_reset_done')),
          name='password_reset'),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('password_reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
               success_url=reverse_lazy('account:password_reset_complete')),
          name='password_reset_confirm'),
     path('password_reset/complete/',
          auth_views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete'),

     # password change
     path('password_change/', views.CustomPasswordChangeView.as_view(),
          name='password_change'),

     path('signup/', views.signup, name='signup'),
     path('profile/', views.profile, name='profile'),
     path('settings/', views.settings, name='settings'),
]

courserepo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('repository.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'CourseRepo Admin'
admin.site.index_title = 'Course Repository Admin'
admin.site.site_title = 'Course Repository administration'

repository/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Level(models.Model):
    year = models.CharField(max_length=10)
    slug = models.SlugField(max_length=10, unique=True)

    def get_absolute_url(self):
        return reverse('level', kwargs={'slug': self.slug})

    def __str__(self):
        return self.year


class Course(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    code = models.CharField(max_length=10)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('course_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class ResourceType(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=100)
    lecturer = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    description = models.TextField()
    image = models.ImageField(upload_to='images')
    document = models.FileField(upload_to='materials')
    resource_type = models.ForeignKey(ResourceType, on_delete=models.PROTECT)
    pages = models.PositiveSmallIntegerField()
    user_library = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='user_materials', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('course_material', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Library(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    materials = models.ManyToManyField(Material)

    class Meta:
        verbose_name_plural = 'Libraries'

    def __str__(self):
        return f"{self.user.username} Library"

templates/partials/_account_nav.html
<div class="card p-3 mb-4">
    <nav class="nav flex-column nav-pills">
        <a class="nav-link {% url 'account:profile' as profile_url %}{% if request.get_full_path == profile_url %}active{% endif %}"
            href="{% url 'account:profile' %}">My Profile</a>
        <a class="nav-link {% url 'account:settings' as settings_url %}{% if request.get_full_path == settings_url %}active{% endif %}"
            href="{% url 'account:settings' %}">Settings</a>
        <a class="nav-link {% url 'account:password_change' as password_change_url %}{% if request.get_full_path == password_change_url %}active{% endif %}"
            href="{% url 'account:password_change' %}">Change Password</a>
    </nav>
</div>

templates/partials/_alert.html
{% if messages %}
{% for message in messages %}
<div class="position-fixed top-0 start-50 translate-middle-x p-3">
    <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" data-bs-delay="10000" role="alert"
        aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">{{ message }}</div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Close"></button>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_course_item.html
<div class="col-lg-4 col-md-3 col-sm-6 col-12 mb-3">
    <a href="{{ course.get_absolute_url }}">{{ course.title }}</a>
    <small class="d-block text-muted py-2">{{ course.material_set.count }} resources</small>
</div>

templates/partials/_material_item.html
<div class="col-lg-3 col-md-6 col-12 mb-3">
    <div class="card shadow-sm h-100">
        <div class="card-body">
            <h5 class="card-title"><a href="{{ material.get_absolute_url }}">{{ material.name }}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ material.course.code }}</h6>
            <p class="card-text">
                <ul class="list-unstyled">
                    <li>Lecturer: <strong>{{ material.lecturer }}</strong></li>
                    <li>Resource Type: <strong>{{ material.resource_type }}</strong></li>
                    <li>Level: <strong>{{ material.course.level }}</strong></li>
                    <li>Pages: <strong>{{ material.pages }}</strong></li>
                </ul>
            </p>
        </div>
    </div>
</div>

templates/partials/_pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Pagination">
    <ul class="pagination justify-content-center">

        {% if page_obj.number > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">First</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">First</span>
        </li>
        {% endif %}

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active">
            <span class="page-link">
                {{ page_num }}
            </span>
        </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Last</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Last</span>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}

templates/partials/_search_filters.html
<form action="{% url 'search' %}" method="get">
    <div class="row">
        <div class="col-lg-3 mb-2">
            <input type="text" class="form-control" placeholder="Name of material" name="name" id="id_name" value="{{ request.GET.name }}">
        </div>
        <div class="col-lg-3 mb-2">
            <input type="text" class="form-control" placeholder="Course" name="course" id="id_course" value="{{ request.GET.course }}">
        </div>
        <div class="col-lg-2 form-group mb-2">
            <select name="level" class="form-select" id="id_level">
                <option value="" selected>-- Select Level --</option>
                {% for level in levels %}
                <option value="{{ level.pk }}">{{ level.year }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-lg-3 form-group mb-2">
            <select name="resource_type" class="form-select" id="id_resource_type">
                <option value="" selected>-- Select Resource Type --</option>
                {% for resource_type in resource_types %}
                <option value="{{ resource_type.pk }}">{{ resource_type.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-lg-1">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>