account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
     # Access     
     path('logout/',
          auth_views.LogoutView.as_view(), name='logout'),
     path('login/',
          auth_views.LoginView.as_view(
               redirect_authenticated_user=True), name='login'),

     # Account activation
     path('activation/sent/',
          views.account_activation_sent,
          name='account_activation_sent'),
     path('activate/<uidb64>/<token>/',
          views.activate,
          name='activate'),

     # password reset with email
     path('password_reset/',
          auth_views.PasswordResetView.as_view(
               success_url=reverse_lazy('account:password_reset_done')),
          name='password_reset'),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('password_reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(
               success_url=reverse_lazy('account:password_reset_complete')),
          name='password_reset_confirm'),
     path('password_reset/complete/',
          auth_views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete'),

     # password change
     path('password_change/', views.CustomPasswordChangeView.as_view(),
          name='password_change'),

     path('signup/', views.signup, name='signup'),
     path('profile/', views.profile, name='profile'),
     path('settings/', views.settings, name='settings'),
]

courserepo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('repository.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'CourseRepo Admin'
admin.site.index_title = 'Course Repository Admin'
admin.site.site_title = 'Course Repository administration'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Course Materials Repository</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}"/>
    <style>
        .alert ul {
            list-style-type: none;
        }
        #hint_id_new_password1 {
            display: none;
        }
        :root {
            --avatar-size: 3rem;
        }
        .circle {
            height: var(--avatar-size);
            width: var(--avatar-size);
        }
        .initials {
            font-size: calc(var(--avatar-size) / 2); /* 50% of parent */
            top: calc(var(--avatar-size) / 4); /* 25% of parent */
        }
    </style>
</head>

<body class="d-flex flex-column min-vh-100">

    <header>
        <div class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
                    <strong>Course Repository</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler"
                    aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggler">
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link {% url 'home' as home_url %}{% if request.get_full_path == home_url %}active{% endif %}" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% url 'materials' as materials_url %}{% if request.get_full_path == materials_url %}active{% endif %}" href="{% url 'materials' %}">Materials</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% url 'courses' as courses_url %}{% if request.get_full_path == courses_url %}active{% endif %}" href="{% url 'courses' %}">Courses</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">Account</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                {% if request.user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'account:profile' %}">My Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:settings' %}">Settings</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'account:signup' %}">Register</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <main>
        {% include 'partials/_alert.html' %}        
        {% block content %} {% endblock content %}
    </main>


    <footer class="text-white py-5 mt-auto bg-dark">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#" class="text-info">Back to top</a>
            </p>
            <p class="mb-1">Course Repository System &copy; Ijeoma Ibeabuchi Kudirat</p>
            <p class="mb-0">Final Year Computer Science Project.</p>
        </div>
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script>
        window.onload = (event) => {
            let myAlert = document.querySelector('.toast');
            let bsAlert = new bootstrap.Toast(myAlert);
            bsAlert.show();
        }
    </script>
    
</body>

</html>

templates/course_detail.html
{% extends "base.html" %}

{% block title %}Materials for {{ course.title }}{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center text-white">
            <h1 class="fw-bolder">Materials for <u>{{ course.title }}</u></h1>
        </div>
    </div>
</section>

<div class="py-5">
    <div class="container">
        <div class="row g-3 mb-5">
            {% for material in materials %}
            {% include 'partials/_material_item.html' %}
            {% empty %}
            <p>No record available.</p>
            {% endfor %}
        </div>
        {% include 'partials/_pagination.html' with page_obj=materials %}
    </div>
</div>


{% endblock %}

templates/course_material.html
{% extends "base.html" %}

{% block title %}{{ material.name }}{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container my-5">
        <div class="text-white">
            <h1 class="fw-bolder">{{ material.name }}</h1>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container">
        <div class="row gx-5">
            <div class="col-lg-4 mb-3">
                <img class="w-100" height="480px" src="{{ material.image.url }}">
            </div>
            <div class="col-lg-8">
                <h5 class="fw-bold text-dark">Description</h5>
                <p>{{ material.description|linebreaks }}</p>

                <hr>

                <h5 class="fw-bold mb-3 text-dark">Information</h5>
                <dl class="row">
                    <dt class="col-3">Course title</dt>
                    <dd class="col-9"><a href="{{ material.course.get_absolute_url }}">{{ material.course }}</a></dd>

                    <dt class="col-3">Course No</dt>
                    <dd class="col-9">{{ material.course.code }}</dd>

                    <dt class="col-3">For</dt>
                    <dd class="col-9">{{ material.course.level }} students</dd>

                    <dt class="col-3">Lecturer</dt>
                    <dd class="col-9">{{ material.lecturer }}</dd>

                    <dt class="col-3">Pages</dt>
                    <dd class="col-9">{{ material.pages }}</dd>

                    <dt class="col-3">Resource Type</dt>
                    <dd class="col-9">{{ material.resource_type }}</dd>
                </dl>

                <hr>

                {% if request.user.is_authenticated %}
                    <a href="{{ material.document.url }}" target="_blank" class="btn btn-info" download> Download </a>
                    {% if added_to_library %}
                        <a href="{% url 'add_to_library' material.id %}" class="btn btn-danger">Remove from library</a>
                    {% else %}
                        <a href="{% url 'add_to_library' material.id %}" class="btn btn-success">Add to library</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'account:login' %}?next={{ material.get_absolute_url }}" class="btn btn-primary">Login to Download</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/courses.html
{% extends "base.html" %}

{% block title %}Browse Courses{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center text-white">
            <h1 class="fw-bolder">Browse Courses</h1>
        </div>
    </div>
</section>

<!-- Courses section -->
<div class="py-5 bg-light">
    <div class="container">
        <div class="card shadow-sm p-3 mb-5">
            <div class="row">
                {% for course in courses %}
                {% include 'partials/_course_item.html' %}
                {% empty %}
                <p>No record available.</p>
                {% endfor %}
            </div>
        </div>
        {% include 'partials/_pagination.html' with page_obj=courses %}
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Welcome Home{% endblock %}

{% block content %}

<!-- Hero section -->
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto mb-3">
            <h1 class="fw-light">Make every study hour count</h1>
            <p class="lead text-muted">Find tens of course-specific study materials, past questions, assignments and lecture slides from Computer science lecturers with the form below.</p>
        </div>

        {% include "partials/_search_filters.html" %}
    </div>
</section>

<!-- Class Levels section -->
<div class="py-5 bg-light">
    <div class="container">
        <div class="row gx-5 justify-content-center mb-5">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Class Levels</h2>
                </div>
            </div>
        </div>
        <div class="row g-3">
            {% for level in levels %}
            <div class="col-lg-3 col-md-6 mb-3">
                <div class="card bg-dark">
                    <a href="{{ level.get_absolute_url }}" class="text-decoration-none">
                        <h5 class="text-white text-center py-3 pt-4">{{ level.year }}</h5>
                    </a>
                </div>
            </div>
            {% empty %}
            <p>No record available.</p>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Popular materials section -->
<div class="py-5">
    <div class="container">
        <div class="row gx-5 justify-content-center mb-5">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Featured Materials</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for material in materials %}
            {% include 'partials/_material_item.html' %}
            {% empty %}
            <p>No record available.</p>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Courses section -->
<div class="py-5 bg-light">
    <div class="container">
        <div class="row gx-5 justify-content-center mb-5">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Featured Courses</h2>
                </div>
            </div>
        </div>
        <div class="card shadow-sm p-3">
            <div class="row">
                {% for course in courses %}
                {% include 'partials/_course_item.html' %}
                {% empty %}
                <p>No record available.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/level.html
{% extends "base.html" %}

{% block title %}Materials for {{ level.year }}{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center text-white">
            <h1 class="fw-bolder">Materials for <u>{{ level.year }}</u></h1>
        </div>
    </div>
</section>

<div class="py-5">
    <div class="container">
        <div class="row g-3 mb-5">
            {% for material in materials %}
            {% include 'partials/_material_item.html' %}
            {% empty %}
            <p>No record available.</p>
            {% endfor %}
        </div>
        {% include 'partials/_pagination.html' with page_obj=materials %}
    </div>
</div>


{% endblock %}

templates/materials.html
{% extends "base.html" %}

{% block title %}Browse Materials{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center text-white">
            <h1 class="fw-bolder">Browse Materials</h1>
        </div>
    </div>
</section>

<div class="py-5">
    <div class="container">
        <div class="row g-3 mb-5">
            {% for material in materials %}
            {% include 'partials/_material_item.html' %}
            {% empty %}
            <p>No record available.</p>
            {% endfor %}
        </div>
        {% include 'partials/_pagination.html' with page_obj=materials %}
    </div>
</div>


{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Profile{% endblock %}

{% block content %}

<section class="py-5">
    <div class="container">
        <div class="row">
            <aside class="col-lg-3">
                {% include 'partials/_account_nav.html' %}
            </aside>
            <div class="col-lg-9">
                <div class="card mb-4">
                    <div class="card-body">
                        <header class="d-md-flex">
                            <div class="flex-shrink-0 circle rounded-circle text-center bg-primary">
                                <span class="initials position-relative lh-1">{{ request.user|make_list|first|title }}</span>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="m-0">{{ request.user.get_full_name|default:request.user.username|title }}
                                </h5>
                                <small>Registered {{ request.user.date_joined|naturalday }}</small>
                            </div>
                            <div>
                                <a href="{% url 'account:settings' %}" class="btn btn-sm btn-outline-primary">Edit Profile</a>
                            </div>
                        </header>
                    </div>
                </div>
                <h4 class="mb-4">My Materials Library</h4>
                <div class="row">
                    {% for material in materials %}
                    {% include 'partials/_material_item.html' %}
                    {% empty %}
                    <p class="text-center mt-5">No material in your library yet.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}

<section class="py-3 bg-dark">
    <div class="container px-5 my-5">
        <div class="text-center text-white">
            <h1 class="fw-bolder mb-4">Search Results</h1>
            {% include "partials/_search_filters.html" %}
        </div>
    </div>
</section>

<div class="py-5">
    <div class="container">
        <div class="row g-3">
            {% for material in materials %}
            {% include 'partials/_material_item.html' %}
            {% empty %}
            <p>Search not found.</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Settings{% endblock %}

{% block content %}

<section class="py-5">
    <div class="container">
        <div class="row">
            <aside class="col-lg-3">
                {% include 'partials/_account_nav.html' %}
            </aside>
            <div class="col-lg-9">
                <div class="card mb-4">
                    <div class="card-body">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="col-lg-6 mb-3">
                                {{ user_form|crispy }}
                                <button class="btn btn-primary" type="submit">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}